---
- name: 'Am I an Adult or a Child?'
  hosts: localhost
  vars:
    age: 25
  tasks:
    - name: I am a Child
      when: 'age < 18'
      command: 'echo "I am a Child"'

    - name: I am an Adult
      when: 'age >= 18'
      command: 'echo "I am an Adult"'